### ISSUE TITLE
Error Message when running Ondsel ES

### ISSUE THREAD

**Issue by KeithSloan** [Ondsel-Development/Ondsel-FirstRun#1]
Not sure where I should be reporting issues with running OndSel ES

So adding here for now.

When opening a file created with FreeCAD 0.21 I get in Report View
```
23:13:10  pyException: Traceback (most recent call last):
  File "/Applications/Ondsel ES.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'freecad.gdml'
23:13:10  pyException: Traceback (most recent call last):
  File "/Applications/Ondsel ES.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'freecad.gdml'
23:13:10  pyException: Traceback (most recent call last):
  File "/Applications/Ondsel ES.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'freecad.gdml'
```
Message is repeated many times.

File
[TestInside8.FCStd.txt](https://github.com/Ondsel-Development/Ondsel-FirstRun/files/14030755/TestInside8.FCStd.txt)

Need to drop txt ( required for github post )from extension.

```
OS: macOS 12.6.8
Word size of Ondsel: 64-bit
Version: 2024.1.0.35694 (Git)
Build type: Release
Branch: flavor
Hash: b070090c6873b3fcf4be9a459219d22edfc4e7cf
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Ondsel-Lens 2024.1.22.01
  * OpenDark 2023.12.17
```

**Comment by sliptonic** [comment]
Note that Ondsel keeps its preferences and installed addons separate from the FreeCAD preferences and addons.
If your documents are using a third party addon, you'll have to install it in ondsel also

**Comment by KeithSloan** [comment]
Okay resolved
